export const wordPictureTypes: Array<[string, string]> = [
  [
    "tree",
    "https://unsplash.com/photos/Bjis2abz9Og/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQxOTQ1NzU1fA&force=true&w=640",
  ],
  [
    "sun",
    "https://unsplash.com/photos/umOVSeWBCNY/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQxOTQ2MzUwfA&force=true&w=640",
  ],
  [
    "cat",
    "https://unsplash.com/photos/PjQ4GoHY7r0/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8NzZ8fGNhdHxlbnwwfHx8fDE3NDIwMDgxNDJ8MA&force=true&w=640",
  ],
  [
    "dog",
    "https://unsplash.com/photos/YOSYrXCholk/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8NDB8fGRvZyUyMHN0YW5kaW5nJTIwb24lMjBiZWR8ZW58MHx8fHwxNzQyMDEwMjA3fDA&force=true&w=640",
  ],
  [
    "plane",
    "https://unsplash.com/photos/7sJbZkVqX9M/download?force=true&w=640",
  ],
  [
    "bird",
    "https://unsplash.com/photos/DPXytK8Z59Y/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQyMDEwMTc5fA&force=true&w=640",
  ],
  [
    "house",
    "https://unsplash.com/photos/QjuJaMH1rEc/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8MTYzfHxob3VzZXxlbnwwfHx8fDE3NDIwMTA3NTh8Mg&force=true&w=640",
  ],
  [
    "car",
    "https://unsplash.com/photos/ZdLFPE0AZBU/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8MzU2fHxjYXJ8ZW58MHx8fHwxNzQyMDEwOTUxfDI&force=true&w=640",
  ],
  [
    "book",
    "https://unsplash.com/photos/SVgX47QIUlc/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8Nnx8b3BlbiUyMGJvb2t8ZW58MHx8fHwxNzQyMDExMDUyfDI&force=true&w=640",
  ],
  [
    "pen",
    "https://unsplash.com/photos/d_eLSvL4v9w/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQyMDExMTIxfA&force=true&w=640",
  ],
  [
    "food",
    "https://unsplash.com/photos/4dQiaWKiL-Y/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQyMDExMjA4fA&force=true&w=640",
  ],
  [
    "water",
    "https://unsplash.com/photos/rrfdqjJWwmU/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQyMDE3NDAxfA&force=true&w=640",
  ],
  [
    "laugh",
    "https://unsplash.com/photos/dnL6ZIpht2s/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQyMDE3MTU2fA&force=true&w=640",
  ],
  [
    "bed",
    "https://unsplash.com/photos/3AvEi1EoIyM/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8MTM2fHxiZWR8ZW58MHx8fHwxNzQyMDMwNDc3fDA&force=true&w=640",
  ],
];
